##
# Services needed to run Magento2 application on Docker
#
# Docker Compose defines required services and attach them together through aliases
##
version: '2'
services:
    web:
        container_name: magento2devbox_web_b13d041c59a1101c95485fed27e4cc4e
        restart: always
        image: magento/magento2devbox-web:latest
        volumes:
          - "./shared/webroot:/home/magento2/magento2"
          - "~/.composer:/home/magento2/.composer"
          - "~/.ssh:/home/magento2/.ssh"
          - "./shared/logs/apache2:/var/log/apache2"
          - "./shared/logs/php-fpm:/var/log/php-fpm"
          - "./shared/.magento-cloud:/home/magento2/.magento-cloud"
          - "./src:/home/magento2/magento2/app/code/community/ChrisQueen/Mage2fb"
        environment:
          - USE_SHARED_WEBROOT=0
          - SHARED_CODE_PATH="/home/magento2/magento2"
          - USE_RABBITMQ=1
          - USE_REDIS_FULL_PAGE_CACHE=1
          - USE_REDIS_CACHE=1
          - USE_REDIS_SESSIONS=1
          - USE_VARNISH=0
          - USE_ELASTICSEARCH=0
#          - MAGENTO_PUBLIC_KEY=3c38629beea40e261f0f3ca477148d98
#          - MAGENTO_PRIVATE_KEY=2f5bb97f41280cb7ee1c47c0f635311f
          - MAGENTO_USE_SOURCES_IN_HOST=0
          - CREATE_SYMLINK_EE=0
          - HOST_CE_PATH=./shared/webroot
          - EE_DIRNAME=magento2ee
          - MAGENTO_DOWNLOAD_SOURCES_COMPOSER=1
          - MAGENTO_EDITION=ce
          - MAGENTO_VERSION=2.1.3
          - MAGENTO_SAMPLE_DATA_INSTALL=1
          - MAGENTO_DOWNLOAD_SOURCES_CLOUD=0
          - MCLOUD_USERNAME=
          - MCLOUD_PASSWORD=
          - MCLOUD_GENERATE_NEW_TOKEN=
          - MCLOUD_PROJECT=
          - MCLOUD_BRANCH=
          - MAGENTO_CRON_RUN=0
          - MAGENTO_DI_COMPILE=0
          - MAGENTO_GRUNT_COMPILE=0
          - MAGENTO_STATIC_CONTENTS_DEPLOY=0
          - MAGENTO_BACKEND_PATH=admin
          - MAGENTO_ADMIN_USER=admin
          - MAGENTO_ADMIN_PASSWORD=admin123
        ports:
          - "80"
          - "22"

    db:
        container_name: magento2devbox_db_b13d041c59a1101c95485fed27e4cc4e
        restart: always
        image: mysql:5.6
        ports:
          - "3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento2
        volumes:
          - "./shared/db:/var/lib/mysql"
          - "./shared/var/logs/mysql:/var/log/mysql"

    redis:
        container_name: magento2devbox_redis_b13d041c59a1101c95485fed27e4cc4e
        restart: always
        image: redis:3.0.7

    rabbit:
        container_name: magento2devbox_rabbit_b13d041c59a1101c95485fed27e4cc4e
        restart: always
        image: rabbitmq:3-management
        ports:
          - "15672"
          - "5672"

